let bridge; let tags=[]; const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m,error=false){const e=$('#toast');e.textContent=m;e.className='toast show'+(error?' error':'');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.className='toast',2800)}
function modal(kind,message,value=''){return new Promise(resolve=>{const m=$('#confirm-modal'),input=$('#confirm-modal-input'),ok=$('#confirm-modal-ok'),cancel=$('#confirm-modal-cancel');$('#confirm-modal-title').textContent=kind==='text'?'编辑情绪标签':'请确认';$('#confirm-modal-message').textContent=message;input.hidden=kind!=='text';input.value=value;const close=result=>{m.hidden=true;ok.onclick=null;cancel.onclick=null;resolve(result)};ok.onclick=()=>close(kind==='text'?input.value:true);cancel.onclick=()=>close(null);m.hidden=false;if(kind==='text'){input.focus();input.select()}else{ok.focus()}})}
const askConfirm=message=>modal('confirm',message).then(result=>result!==null);const askText=(message,value)=>modal('text',message,value)
const get=(e,p={})=>bridge.apiGet(e,p); const post=(e,b={})=>bridge.apiPost(e,b);
function renderOptions(root,selected=[]){root.innerHTML=tags.filter(t=>t.kind==='emotion').map(t=>`<button type="button" class="tag-option ${selected.includes(Number(t.id))?'selected':''}" data-tag-id="${t.id}">${esc(t.name)}</button>`).join('')||'<small class="muted">暂无情绪标签</small>'}
function selectedTagIds(root){return [...root.querySelectorAll('[data-tag-id].selected')].map(x=>Number(x.dataset.tagId))}
function updateTrigger(root){const names=[...root.querySelectorAll('[data-tag-id].selected')].map(x=>x.textContent.trim());root.querySelector('[data-tag-trigger]')?.replaceChildren(document.createTextNode(names.length?names.join('、'):'选择情绪标签'))}
function setupTagSelects(){document.querySelectorAll('.tag-select').forEach(root=>{const trigger=root.querySelector('[data-tag-trigger]');trigger.onclick=()=>root.classList.toggle('open');root.querySelector('[data-tag-search]').oninput=e=>{const q=e.target.value.trim().toLowerCase();root.querySelectorAll('.tag-option').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(q))};root.querySelector('.tag-options').onclick=e=>{const option=e.target.closest('.tag-option');if(!option)return;option.classList.toggle('selected');updateTrigger(root)};updateTrigger(root)});if(!window.__tagSelectOutside){document.addEventListener('click',e=>{if(!e.target.closest('.tag-select'))document.querySelectorAll('.tag-select.open').forEach(x=>x.classList.remove('open'))});window.__tagSelectOutside=true}}
function setupEmotionFilter(){const root=$('#emotion-filter'),trigger=$('#emotion-trigger'),select=$('#emotion'),search=$('#emotion-filter-search'),options=$('#emotion-filter-options');trigger.onclick=()=>root.classList.toggle('open');search.oninput=()=>{const q=search.value.trim().toLowerCase();options.querySelectorAll('button').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(q))};options.onclick=e=>{const option=e.target.closest('button');if(!option)return;select.value=option.dataset.value;trigger.textContent=option.textContent;root.classList.remove('open');refresh()};if(!window.__emotionFilterOutside){document.addEventListener('click',e=>{if(!e.target.closest('#emotion-filter'))root.classList.remove('open')});window.__emotionFilterOutside=true}}
function renderTags(){const emotions=tags.filter(t=>t.kind==='emotion');$('#emotion').innerHTML='<option value="">全部情绪</option>'+emotions.map(t=>`<option value="${esc(t.name)}">${esc(t.name)}</option>`).join('');$('#emotion-filter-options').innerHTML='<button type="button" data-value="">全部情绪</button>'+emotions.map(t=>`<button type="button" data-value="${esc(t.name)}">${esc(t.name)}</button>`).join('');renderOptions($('#emotion-options'));$('#tag-count').textContent=`共 ${emotions.length} 个`;$('#tags').innerHTML=emotions.map(t=>`<div class="tag-item"><span>${esc(t.name)}<em>情绪</em></span><div class="tag-actions"><button data-rename="${t.id}">重命名</button><button class="danger" data-delete="${t.id}">删除</button></div></div>`).join('')||'<div class="empty">还没有标签</div>';document.querySelectorAll('[data-rename]').forEach(b=>b.onclick=renameTag);document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=deleteTag);setupTagSelects();setupEmotionFilter()}
async function loadTags(){try{tags=(await get('tags')).tags||[];renderTags();$('#stat-emotions').textContent=tags.length}catch(e){toast('标签加载失败：'+(e.message||'请求失败'),true)}}
async function renameTag(e){const id=e.currentTarget.dataset.rename;const old=tags.find(t=>String(t.id)===id);const name=await askText('请输入新的情绪标签',old?.name||'');if(!name||name.trim()===old?.name)return;try{await post(`tags/${id}/rename`,{name:name.trim()});toast('标签已重命名');await loadTags();await refresh()}catch(x){toast('重命名失败：'+(x.message||'请求失败'),true)}}
async function deleteTag(e){if(!await askConfirm('删除标签后不可恢复，确定继续？'))return;try{await post(`tags/${e.currentTarget.dataset.delete}/delete`,{});toast('标签已删除');await loadTags()}catch(x){toast('删除失败：'+(x.message||'该标签仍被图片使用'),true)}}
function formatBytes(n){if(!n)return '—';if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
async function refresh(){try{const p={};for(const id of ['filename','enabled','emotion','content'])if($('#'+id).value)p[id]=$('#'+id).value;const images=(await get('images',p)).images||[];$('#images').innerHTML=images.length?images.map(x=>`<article class="image-card"><div class="image-preview" data-preview-id="${x.id}"><span class="preview-loading">加载预览中…</span></div><div class="image-info"><label class="image-select"><input type="checkbox" class="image-checkbox" data-image-select="${x.id}" data-image-enabled="${x.enabled?'1':'0'}"> 选择图片</label><div class="image-name" title="${esc(x.original_filename)}">${esc(x.original_filename)}</div><div class="image-meta"><span>${formatBytes(x.size_bytes)}</span><span class="${x.enabled?'status-on':'status-off'}">${x.enabled?'● 启用':'● 禁用'}</span></div><label class="card-description">内容描述<input data-description="${x.id}" value="${esc(x.content_description)}" maxlength="200"></label><div class="tag-select card-tag-select" data-tag-select="${x.id}"><button type="button" class="tag-select-trigger" data-tag-trigger="${x.id}">${x.emotion_tags?.length?esc(x.emotion_tags.join('、')):'选择情绪标签'}</button><div class="tag-select-menu" data-tag-menu="${x.id}"><input class="tag-search" data-tag-search="${x.id}" placeholder="搜索情绪标签…"><div class="tag-options">${tags.filter(t=>t.kind==='emotion').map(t=>`<button type="button" class="tag-option ${x.emotion_tags?.includes(t.name)?'selected':''}" data-image="${x.id}" data-emotion="${t.id}" data-tag-id="${t.id}">${esc(t.name)}</button>`).join('')}</div></div></div><div class="card-actions"><button class="primary compact" data-save="${x.id}">保存修改</button></div></div></article>`).join(''):'<div class="empty">暂无符合条件的图片</div>';$('#stat-total').textContent=images.length;$('#stat-enabled').textContent=images.filter(x=>x.enabled).length;$('#stat-content').textContent=images.filter(x=>String(x.content_description||'').trim()).length;setupTagSelects();document.querySelectorAll('[data-save]').forEach(b=>b.onclick=saveImage);document.querySelectorAll('.image-checkbox').forEach(b=>b.onchange=updateBulkState);document.querySelectorAll('[data-preview-id]').forEach(async b=>{const x=images.find(i=>String(i.id)===b.dataset.previewId);if(x)await loadPreview(x)});updateBulkState()}catch(e){toast('图库加载失败：'+(e.message||'请求失败'),true)}}
async function loadPreview(x){const b=document.querySelector(`[data-preview-id="${x.id}"]`);try{const r=await get(`images/${x.id}/preview`);const i=document.createElement('img');i.src=r.data_url;i.alt=x.original_filename;b.replaceChildren(i)}catch(e){b.innerHTML='<span class="preview-error">预览加载失败</span>'}}
async function saveImage(e){const id=e.currentTarget.dataset.save;const tag_ids=selectedTagIds(document.querySelector(`[data-tag-select="${id}"]`));const content_description=$(`[data-description="${id}"]`).value;const b=e.currentTarget;b.disabled=true;try{await post(`images/${id}/tags`,{tag_ids,content_description});toast('图片信息已保存');await refresh()}catch(x){toast('保存失败：'+(x.message||'请求失败'),true)}finally{b.disabled=false}}
async function toggleImage(e){const b=e.currentTarget;b.disabled=true;try{await post(`images/${b.dataset.enabled}/enabled`,{enabled:b.dataset.value==='1'});toast('图片状态已更新');await refresh()}catch(x){toast('状态更新失败：'+(x.message||'请求失败'),true)}finally{b.disabled=false}}
async function deleteImage(e){if(!await askConfirm('删除后不可恢复，图片文件和情绪关联都会被删除。确定继续？'))return;try{await post(`images/${e.currentTarget.dataset.imgDelete}/delete`,{});toast('图片已删除');await refresh()}catch(x){toast('删除失败：'+(x.message||'请求失败'),true)}}
function selectedImageIds(){return [...document.querySelectorAll('.image-checkbox:checked')].map(x=>Number(x.dataset.imageSelect))}
function selectedImageBoxes(){return [...document.querySelectorAll('.image-checkbox:checked')]}
function updateBulkState(){const boxes=[...document.querySelectorAll('.image-checkbox')],selected=selectedImageBoxes(),all=$('#select-all'),enabled=selected.filter(x=>x.dataset.imageEnabled==='1').length,disabled=selected.length-enabled;$('#selected-count').textContent=`已选 ${selected.length} 张`;$('#bulk-enable').disabled=!disabled;$('#bulk-disable').disabled=!enabled;$('#bulk-delete').disabled=!selected.length;if(all){all.checked=boxes.length>0&&boxes.every(x=>x.checked);all.indeterminate=selected.length>0&&selected.length<boxes.length}}
async function bulkEnable(){const ids=selectedImageBoxes().filter(x=>x.dataset.imageEnabled==='0').map(x=>Number(x.dataset.imageSelect));if(!ids.length)return;const b=$('#bulk-enable');b.disabled=true;try{await post('images/batch/enabled',{image_ids:ids,enabled:true});toast(`已启用 ${ids.length} 张图片`);await refresh()}catch(e){toast('批量启用失败：'+(e.message||'请求失败'),true)}finally{b.disabled=false}}
async function bulkDisable(){const ids=selectedImageBoxes().filter(x=>x.dataset.imageEnabled==='1').map(x=>Number(x.dataset.imageSelect));if(!ids.length)return;const b=$('#bulk-disable');b.disabled=true;try{await post('images/batch/enabled',{image_ids:ids,enabled:false});toast(`已禁用 ${ids.length} 张图片`);await refresh()}catch(e){toast('批量禁用失败：'+(e.message||'请求失败'),true)}finally{b.disabled=false}}
async function bulkDelete(){const ids=selectedImageIds();if(!ids.length){toast('请先选择要删除的图片',true);return}if(!await askConfirm(`删除后不可恢复，将删除选中的 ${ids.length} 张图片及其关联。确定继续？`))return;const b=$('#bulk-delete');b.disabled=true;try{await post('images/batch/delete',{image_ids:ids});toast(`已删除 ${ids.length} 张图片`);await refresh()}catch(e){toast('批量删除失败：'+(e.message||'请求失败'),true)}finally{b.disabled=false}}
$('#select-all').onchange=()=>{document.querySelectorAll('.image-checkbox').forEach(x=>x.checked=$('#select-all').checked);updateBulkState()};$('#bulk-enable').onclick=bulkEnable;$('#bulk-disable').onclick=bulkDisable;$('#bulk-delete').onclick=bulkDelete;$('#file').onchange=()=>{const f=$('#file').files[0];$('#preview').innerHTML=f?`<img src="${URL.createObjectURL(f)}" alt="预览">`:''};$('#search').onclick=refresh;$('#refresh').onclick=()=>{loadTags();refresh()};$('#reset').onclick=()=>{['filename','enabled','emotion','content'].forEach(id=>$('#'+id).value='');refresh()};$('#add-tag').onclick=async()=>{const name=$('#tag-name').value.trim();if(!name){$('#tag-message').textContent='请输入标签名称';return}try{await post('tags',{name,kind:'emotion'});$('#tag-name').value='';toast('标签新增成功');await loadTags()}catch(e){toast('新增失败：'+(e.message||'标签可能已存在'),true)}};
$('#upload').onclick=async()=>{const f=$('#file').files[0],description=$('#upload-description').value.trim(),root=document.querySelector('[data-tag-select="upload"]'),ids=selectedTagIds(root);if(!f)return $('#message').textContent='请先选择图片';if(!description)return $('#message').textContent='请填写内容描述';if(!ids.length)return $('#message').textContent='请至少选择一个情绪标签';const b=$('#upload');b.disabled=true;$('#message').textContent='正在上传…';try{const u=await bridge.upload('upload',f);if(!u?.token)throw Error('上传接口未返回令牌');await post('upload/commit',{token:u.token,filename:f.name,content_description:description,tag_ids:ids});toast('图片上传成功');$('#file').value='';$('#upload-description').value='';$('#preview').innerHTML='';root.querySelectorAll('.tag-option').forEach(x=>x.classList.remove('selected'));updateTrigger(root);await refresh()}catch(e){$('#message').textContent='上传失败：'+(e.message||'请求失败');toast('图片上传失败',true)}finally{b.disabled=false}};
(async()=>{try{bridge=window.AstrBotPluginPage;if(!bridge)throw Error('页面桥接未注入');await bridge.ready();await loadTags();await refresh()}catch(e){toast('页面初始化失败：'+e.message,true);$('#boot-error').hidden=false;$('#boot-error').textContent='页面初始化失败：'+e.message}})();